<?php
$akses_role = array(
  1 => array(
    'home' => array('is_write' => 0, 'is_read' => 1),
    'user' => array('is_write' => 1, 'is_read' => 1),
    'data_master' => array('is_write' => 0, 'is_read' => 1),
    'bahan_utama_atap' => array('is_write' => 1, 'is_read' => 1),
    'bahan_bangunan' => array('is_write' => 1, 'is_read' => 1),
    'bahan_jendela' => array('is_write' => 1, 'is_read' => 1),
    'bahan_atap' => array('is_write' => 1, 'is_read' => 1),
    'bahan_dinding' => array('is_write' => 1, 'is_read' => 1),
    'bahan_kusen' => array('is_write' => 1, 'is_read' => 1),
    'bahan_penutup_dinding' => array('is_write' => 1, 'is_read' => 1),
    'bahan_penutup_lantai' => array('is_write' => 1, 'is_read' => 1),
    'bahan_plafond' => array('is_write' => 1, 'is_read' => 1),
    'pola_ruang' => array('is_write' => 1, 'is_read' => 1),
    'struktur_atap' => array('is_write' => 1, 'is_read' => 1),
    'struktur_kolom' => array('is_write' => 1, 'is_read' => 1),
    'struktur_balok' => array('is_write' => 1, 'is_read' => 1),
    'struktur_lantai' => array('is_write' => 1, 'is_read' => 1),
    'struktur_pondasi' => array('is_write' => 1, 'is_read' => 1),
    'struktur_bangunan' => array('is_write' => 1, 'is_read' => 1),
    'kategori_kerusakan' => array('is_write' => 1, 'is_read' => 1),
    'tingkat_kerusakan' => array('is_write' => 1, 'is_read' => 1),
    'kategori_bangunan' => array('is_write' => 1, 'is_read' => 1),
    'keberaturan_bangunan' => array('is_write' => 1, 'is_read' => 1),
    'perda_peraturan' => array('is_write' => 1, 'is_read' => 1),
    'bentuk_bangunan' => array('is_write' => 1, 'is_read' => 1),
    'data_bangunan' => array('is_write' => 1, 'is_read' => 1),
    'data_survey' => array('is_write' => 1, 'is_read' => 1),
    'peta' => array('is_write' => 1, 'is_read' => 1),
    'report' => array('is_write' => 1, 'is_read' => 1),
    'grafik' => array('is_write' => 1, 'is_read' => 1),
    'prosentase_bangunan' => array('is_write' => 1, 'is_read' => 1),
    'logactivity' => array('is_write' => 1, 'is_read' => 1),
  ),
  2 => array(
    'home' => array('is_write' => 0, 'is_read' => 1),
    'user' => array('is_write' => 0, 'is_read' => 0),
    'data_master' => array('is_write' => 0, 'is_read' => 1),
    'bahan_utama_atap' => array('is_write' => 1, 'is_read' => 1),
    'bahan_bangunan' => array('is_write' => 1, 'is_read' => 1),
    'bahan_jendela' => array('is_write' => 1, 'is_read' => 1),
    'bahan_atap' => array('is_write' => 1, 'is_read' => 1),
    'bahan_dinding' => array('is_write' => 1, 'is_read' => 1),
    'bahan_kusen' => array('is_write' => 1, 'is_read' => 1),
    'bahan_penutup_dinding' => array('is_write' => 1, 'is_read' => 1),
    'bahan_penutup_lantai' => array('is_write' => 1, 'is_read' => 1),
    'bahan_plafond' => array('is_write' => 1, 'is_read' => 1),
    'pola_ruang' => array('is_write' => 1, 'is_read' => 1),
    'struktur_atap' => array('is_write' => 1, 'is_read' => 1),
    'struktur_kolom' => array('is_write' => 1, 'is_read' => 1),
    'struktur_balok' => array('is_write' => 1, 'is_read' => 1),
    'struktur_lantai' => array('is_write' => 1, 'is_read' => 1),
    'struktur_pondasi' => array('is_write' => 1, 'is_read' => 1),
    'struktur_bangunan' => array('is_write' => 1, 'is_read' => 1),
    'kategori_kerusakan' => array('is_write' => 1, 'is_read' => 1),
    'tingkat_kerusakan' => array('is_write' => 1, 'is_read' => 1),
    'kategori_bangunan' => array('is_write' => 1, 'is_read' => 1),
    'keberaturan_bangunan' => array('is_write' => 1, 'is_read' => 1),
    'perda_peraturan' => array('is_write' => 1, 'is_read' => 1),
    'bentuk_bangunan' => array('is_write' => 1, 'is_read' => 1),
    'data_bangunan' => array('is_write' => 1, 'is_read' => 1),
    'data_survey' => array('is_write' => 1, 'is_read' => 1),
    'peta' => array('is_write' => 0, 'is_read' => 0),
    'report' => array('is_write' => 0, 'is_read' => 0),
    'grafik' => array('is_write' => 0, 'is_read' => 0),
    'prosentase_bangunan' => array('is_write' => 0, 'is_read' => 0),
  ),
  3 => array(
    'home' => array('is_write' => 0, 'is_read' => 1),
    'user' => array('is_write' => 0, 'is_read' => 0),
    'data_master' => array('is_write' => 0, 'is_read' => 0),
    'bahan_utama_atap' => array('is_write' => 0, 'is_read' => 0),
    'bahan_bangunan' => array('is_write' => 0, 'is_read' => 0),
    'bahan_jendela' => array('is_write' => 0, 'is_read' => 0),
    'kategori_bangunan' => array('is_write' => 0, 'is_read' => 0),
    'keberaturan_bangunan' => array('is_write' => 0, 'is_read' => 0),
    'perda_peraturan' => array('is_write' => 0, 'is_read' => 0),
    'bentuk_bangunan' => array('is_write' => 0, 'is_read' => 0),
    'data_bangunan' => array('is_write' => 0, 'is_read' => 1),
    'data_survey' => array('is_write' => 0, 'is_read' => 1),
    'pola_ruang' => array('is_write' => 0, 'is_read' => 0),
    'peta' => array('is_write' => 0, 'is_read' => 1),
    'report' => array('is_write' => 0, 'is_read' => 1),
    'grafik' => array('is_write' => 0, 'is_read' => 1),
    'prosentase_bangunan' => array('is_write' => 0, 'is_read' => 0),
  ),
);
$config['role_akses'] = $akses_role;
?>
